---
- hosts: clients
  any_errors_fatal: true
  vars_files:
      - play-vars-ycsbsmart.yml  
  vars:
    tmux_client_session: ycsbclient


  tasks:
    
    - name: Check if tmux client is running
      shell: test -n "$(tmux ls | grep {{tmux_client_session}})" && echo "yes" || echo "no"
      register: is_tmux_running

    - name: Stop clients
      when: is_tmux_running.stdout == "yes"
      shell: 
        tmux kill-session -t  "{{tmux_client_session}}"

    - name: Wait while service stops
      pause:
        seconds: 1
    
    - name: Look for client processes
      shell: test -n "$(ps ax | grep bftsmart.demo.ycsb.YCSBClient | grep -v grep )" && echo "yes" || echo "no"
      register: is_running
  
    - name: Check if client process is running
      when: is_running.stdout == "yes"
      fail: msg="Client is still running. Run this again."

    - name: remove old state
      file: 
        path: "{{bftsmart_install_dir}}/config/currentView" 
        state: absent

