- import_playbook: play-init.yml

- hosts: clients, leader, replicas
  become: yes
  any_errors_fatal: true
  vars_files:
      - play-vars-ycsbsmart.yml

  roles:
    - role: Comcast.sdkman
      sdkman_dir: "{{ sdkman_folder }}"
      sdkman_auto_answer: true
      sdkman_update: true
      # sdkman_uninstall_packages:
      #   - { candidate: java, version: 1.8.9 }
      #   - { candidate: ant, version: '3.5' }
      sdkman_install_packages:
        - { candidate: java, version: "{{ java_version }}" }
        - { candidate: ant, version: "{{ ant_version }}" }
      # sdkman_defaults:
      #   gradle: '3.5'
      #   maven: 3.3.9
      sdkman_flush_caches_before:
        - temp
      sdkman_flush_caches_after:
        - archives
        - broadcast
        - candidates
        - temp
  
  post_tasks:
    - name: Ensure presence of profile
      file: state=touch path=~/.profile

    - name: Add sdkman in .profile
      lineinfile: 
        path: ~/.profile 
        regexp: '\[\[ \-s \"{{sdkman_folder}}\/.*'
        line: '[[ -s "{{sdkman_folder}}/bin/sdkman-init.sh" && ! $(which sdkman-init.sh) ]] && source "{{sdkman_folder}}/bin/sdkman-init.sh"'

    - name: Add sdkman in .bashrc
      lineinfile: 
        path: ~/.bashrc 
        regexp: '\[\[ \-s \"{{sdkman_folder}}\/.*'
        line: '[[ -s "{{sdkman_folder}}/bin/sdkman-init.sh" && ! $(which sdkman-init.sh) ]] && source "{{sdkman_folder}}/bin/sdkman-init.sh"'
