
---
- import_playbook: play-init.yml

- name: YCSB deployment
  hosts: clients, leader, replicas
  gather_facts: False
  become: no
  any_errors_fatal: true
  vars_files:
    - play-vars-ycsbsmart.yml


  tasks:
    # the init playbook creates the environment
    # - name: Create environment folder
    #   file: 
    #     path: "{{ item }}"
    #     state: directory
    #   with_items:
    #     - "{{ default_install_dir }}"
    #     - "{{ credentials_dir }}"

    - name: Checkout bftsmart from repository
      git:
        repo: https://github.com/danielporto/bftsmart.git
        dest: "{{ bftsmart_install_dir }}"
        force: yes

    - name: Remove old compilation and jar
      file: 
        path: "{{ item }}"
        state: absent    
      with_items:
          - '{{ bftsmart_install_dir }}/bin/bftsmart'
          - '{{ bftsmart_install_dir }}/bin/BFT-SMaRt.jar'


    - name: Build a new Jar
      shell: 
        tmux -f {{ default_install_dir }}/tmux.conf new-session -d -s build "bash -lc 'ant'"
      args:
        chdir: '{{ bftsmart_install_dir }}'
        executable: /bin/bash

    - name: Wait while ant compiles the new jar
      pause:
        seconds: 10

    - name: Ensure the presence of a new jar
      file: 
        path: '{{ bftsmart_install_dir }}/bin/BFT-SMaRt.jar'
        state: file    


    - name: remove old state
      file: 
        path: '{{ bftsmart_install_dir }}/config/currentView' 
        state: absent